In [4]:
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from keras.layers import Dropout
from keras.optimizers import RMSprop
from sklearn.cross_validation import cross_val_score, KFold
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import math
from keras.models import load_model
import os
from scipy.io import loadmat

sub=['F1','F2','M1','M2']
fold=['Fold1','Fold2','Fold3','Fold4']
# sub = ['M2']
# fold = ['Fold1']
seg='Upper'
print('Processing!!!')
mat1 = loadmat(seg+'/'+"best_per_all.mat")
best = mat1['best_per_all']
for s in sub:
    for f in fold:
        ind = fold.index(f)
        inds = sub.index(s)
        p = best[inds][0][0][ind][0][0]
        print(s+' and '+ f + ' and ' + str(p))
        mat = loadmat(seg+'/'+s+'/'+"pxl_np_"+str(p)+".mat")
        np_fold = mat['pxl_np']
        model = load_model(seg+'/'+s+'/'+f+'/'+'Model_GridWise_dev_'+str(p)+'.hdf5')
#             dataset = pandas.read_csv(seg+'/'+s+'/'+f+'/'+"Grid_Wise_Test_"+str(p)+".csv", delimiter=",",header = None)            
#             dataset.fillna(dataset.mean(), inplace=True)
#             dataset = dataset.as_matrix(columns = None)
        dataset = pandas.read_csv(seg+'/'+s+'/'+f+'/'+"Test_Intensity_Data.csv", delimiter=",",header = None)
        dataset.fillna(dataset.mean(), inplace=True)
        dataset = dataset.as_matrix(columns = None)
        np = np_fold[0,ind][1][0][0]
        print(np)
        possi = []
        for i in range(0,np+1):
            possi.append(numpy.round(model.predict(dataset[:,i*(np+1):(i+1)*(np+1)]),decimals=3))
        possi = numpy.squeeze(numpy.asarray(possi))
        numpy.savetxt(seg+'/'+s+'/'+f+'/'+"Pred_Data_Grid.csv", possi, delimiter=",")
        possi = []
        mat = []
        dataset = []
print('Done!!!')

Processing!!!
F1 and Fold1 and 74
6
F1 and Fold2 and 77
6
F1 and Fold3 and 83
8
F1 and Fold4 and 80
6
F2 and Fold1 and 86
8
F2 and Fold2 and 85
8
F2 and Fold3 and 90
8
F2 and Fold4 and 87
8
M1 and Fold1 and 86
8
M1 and Fold2 and 88
8
M1 and Fold3 and 90
8
M1 and Fold4 and 92
10
M2 and Fold1 and 92
10
M2 and Fold2 and 86
8
M2 and Fold3 and 86
8
M2 and Fold4 and 81
6
Done!!!


In [61]:
a = a1[k].reshape(1,l1)
a = numpy.array([numpy.concatenate(i, axis=0) for i in a])
a = numpy.squeeze(a)
print(a[0])
pred = numpy.round(model.predict(a),decimals=3)
pred[5]
possi.shape

[0.68996384 0.66442408 0.6089363  0.5553897  0.41958738 0.37956538
 0.36963183 0.13224264 0.35510246 0.34185546 0.35028507]


(11, 17040)

In [19]:
from scipy.io import loadmat
import numpy
mat1 = loadmat("Autorun_Ton1/best_per_all.mat")
best = mat1['best_per_all']
sub = 0
fold = 3
print(best)
print(best[sub][0][0][fold][0][0])

[[array([[array([[96]], dtype=uint8), array([[95]], dtype=uint8),
        array([[95]], dtype=uint8), array([[98]], dtype=uint8)]],
      dtype=object)]
 [array([[array([[95]], dtype=uint8), array([[95]], dtype=uint8),
        array([[97]], dtype=uint8), array([[95]], dtype=uint8)]],
      dtype=object)]
 [array([[array([[96]], dtype=uint8), array([[95]], dtype=uint8),
        array([[95]], dtype=uint8), array([[96]], dtype=uint8)]],
      dtype=object)]
 [array([[array([[95]], dtype=uint8), array([[95]], dtype=uint8),
        array([[95]], dtype=uint8), array([[95]], dtype=uint8)]],
      dtype=object)]]
98
